### ISSUE TITLE
cineaste crash when rotate screen during load series  

### ISSUE THREAD

**Issue by muhammadarif1** [spacepandas/cineaste-android#27]
#### EXPECTED BEHAVIOR
  when users want to add a list of new series users should be able to add in various screen conditions

#### ACTUAL BEHAVIOR
when the user adds a new series then the user rotates the screen when the series list loading process is running this application will crash and will take the user back to the front page launcher

####  HOW TO REPRODUCE 
 - download cinetaste from playstore
- after that launch the app
- select series section
- then select watch list
- then click option `` `+` ``
- when the loading process is running rotation screen of your smartphone and see if this application will crash

 BROWSER : CINE TASTE V 2.4.0
DEVICE        : SAMSUNG J 5  PRIME ANDROID 7.0 

#### BUG RECORDING 
https://youtu.be/14kWUP-zk8M

#### LOG CAT FILE 
```FATAL EXCEPTION: main
Process: de.cineaste.android, PID: 2096
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.cineaste.android/de.cineaste.android.activity.SeriesSearchActivity}: java.lang.IllegalStateException: savedInstanceState.getString("query", null) must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4038)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5376)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.IllegalStateException: savedInstanceState.getString("query", null) must not be null
	at de.cineaste.android.activity.AbstractSearchActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6012)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 11 more```

**Comment by marcelgross90** [comment]
Will be fixed with next version
