### ISSUE TITLE
crash in landscape mode when pressing "movie watched"

### ISSUE THREAD

**Issue by muhammadarif1** [spacepandas/cineaste-android#29]
##### expected behavior
this application should allow users to use various features in different screen states
#### ACTUAL BEHAVIOR 
when the user presses the "movie watched" button in landscape mode this application will crash
#### HOW TO REPPRODUCE 
- download cinetaste from playstore
- launch the app
- click the + button
- Choose any movie
- change your phone's mode of mode from portrait mode to landscape mode and select "movies watched" button and record the bug
#### bug recording 

https://youtu.be/hxmYwB8WBTM 

#### log cat file ```FATAL EXCEPTION: main
Process: de.cineaste.android, PID: 14059
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.cineaste.android/de.cineaste.android.activity.MovieSearchActivity}: java.lang.IllegalStateException: savedInstanceState.getString("query", null) must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4038)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5376)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by: java.lang.IllegalStateException: savedInstanceState.getString("query", null) must not be null
	at de.cineaste.android.activity.AbstractSearchActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6012)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)```

**Comment by marcelgross90** [comment]
Will be fixed with next version
